<a href="https://colab.research.google.com/github/reshmajayaghosh/ICT/blob/main/Case_Study_Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [50]:
import numpy as np
import pandas as pd

In [51]:
df = pd.read_csv("/content/drive/MyDrive/ICT DSA Python/auto-mpg.csv")

In [52]:
df.head()

mpg  cylinders  displacement horsepower  weight  acceleration  model year  \
0  18.0          8         307.0        130    3504          12.0          70   
1  15.0          8         350.0        165    3693          11.5          70   
2  18.0          8         318.0        150    3436          11.0          70   
3  16.0          8         304.0        150    3433          12.0          70   
4  17.0          8         302.0        140    3449          10.5          70   

   origin                   car name  
0       1  chevrolet chevelle malibu  
1       1          buick skylark 320  
2       1         plymouth satellite  
3       1              amc rebel sst  
4       1                ford torino

In [53]:
df.columns

Index(['mpg', 'cylinders', 'displacement', 'horsepower', 'weight',
       'acceleration', 'model year', 'origin', 'car name'],
      dtype='object')

# **NumPy Problems**

1. **Basic Array Operations**


**Convert the mpg column into a NumPy array and calculate:**

○ The mean, median, and standard deviation of mpg.

In [54]:
mpg_array = df['mpg'].to_numpy()

mean_mpg = np.mean(mpg_array)
median_mpg = np.median(mpg_array)
std_mpg = np.std(mpg_array)

mean_mpg, median_mpg, std_mpg


(np.float64(23.514572864321607),
 np.float64(23.0),
 np.float64(7.806159061274433))

**The number of cars with mpg greater than 25.**

In [55]:
count_high_mpg = np.sum(mpg_array > 25)
count_high_mpg


np.int64(158)

2. **Filtering**



Using NumPy, filter all cars with more than 6 cylinders.

Return the corresponding car_name as a list.

In [56]:
df.loc[df['cylinders'] > 6, 'car name'].tolist()


['chevrolet chevelle malibu',
 'buick skylark 320',
 'plymouth satellite',
 'amc rebel sst',
 'ford torino',
 'ford galaxie 500',
 'chevrolet impala',
 'plymouth fury iii',
 'pontiac catalina',
 'amc ambassador dpl',
 'dodge challenger se',
 "plymouth 'cuda 340",
 'chevrolet monte carlo',
 'buick estate wagon (sw)',
 'ford f250',
 'chevy c20',
 'dodge d200',
 'hi 1200d',
 'chevrolet impala',
 'pontiac catalina brougham',
 'ford galaxie 500',
 'plymouth fury iii',
 'dodge monaco (sw)',
 'ford country squire (sw)',
 'pontiac safari (sw)',
 'chevrolet impala',
 'pontiac catalina',
 'plymouth fury iii',
 'ford galaxie 500',
 'amc ambassador sst',
 'mercury marquis',
 'buick lesabre custom',
 'oldsmobile delta 88 royale',
 'chrysler newport royal',
 'amc matador (sw)',
 'chevrolet chevelle concours (sw)',
 'ford gran torino (sw)',
 'plymouth satellite custom (sw)',
 'buick century 350',
 'amc matador',
 'chevrolet malibu',
 'ford gran torino',
 'dodge coronet custom',
 'mercury marquis brou

3. **Statistical Analysis**

Compute the 25th, 50th, and 75th percentiles of the weight column using NumPy.


In [57]:
weight_array = df['weight'].to_numpy()

percentiles = np.percentile(weight_array, [25, 50, 75])
percentiles


array([2223.75, 2803.5 , 3608.  ])

4. **Array Manipulation**

Convert the acceleration column into a NumPy array and normalize its values (scale between 0 and 1).

In [58]:
acc_array = df['acceleration'].to_numpy()

acc_min = np.min(acc_array)
acc_max = np.max(acc_array)

acc_normalized = (acc_array - acc_min) / (acc_max - acc_min)
acc_normalized


array([0.23809524, 0.20833333, 0.17857143, 0.23809524, 0.14880952,
       0.11904762, 0.05952381, 0.0297619 , 0.11904762, 0.0297619 ,
       0.11904762, 0.        , 0.08928571, 0.11904762, 0.41666667,
       0.44642857, 0.44642857, 0.47619048, 0.38690476, 0.74404762,
       0.56547619, 0.38690476, 0.56547619, 0.26785714, 0.41666667,
       0.35714286, 0.41666667, 0.32738095, 0.625     , 0.38690476,
       0.44642857, 0.35714286, 0.6547619 , 0.29761905, 0.44642857,
       0.44642857, 0.44642857, 0.44642857, 0.23809524, 0.20833333,
       0.32738095, 0.29761905, 0.20833333, 0.23809524, 0.23809524,
       0.32738095, 0.6547619 , 0.41666667, 0.38690476, 0.35714286,
       0.35714286, 0.68452381, 0.38690476, 0.6547619 , 0.5952381 ,
       0.6547619 , 0.74404762, 0.44642857, 0.53571429, 0.92261905,
       0.68452381, 0.50595238, 0.23809524, 0.23809524, 0.32738095,
       0.29761905, 0.20833333, 0.17857143, 0.32738095, 0.32738095,
       0.26785714, 0.32738095, 0.26785714, 0.35714286, 0.47619

5. **Broadcasting**

Increase all horsepower values by 10% and store the updated values in a new NumPy array. Handle missing data (if any) by replacing it with the mean of the column before applying the increase.

In [59]:
df['horsepower'] = pd.to_numeric(df['horsepower'], errors='coerce')

In [60]:
horsepower_array = df['horsepower'].to_numpy()

# Replace missing values with mean
hp_mean = np.nanmean(horsepower_array)
horsepower_array = np.where(np.isnan(horsepower_array), hp_mean, horsepower_array)

# Increase by 10%
horsepower_updated = horsepower_array * 1.10
horsepower_updated


array([143.        , 181.5       , 165.        , 165.        ,
       154.        , 217.8       , 242.        , 236.5       ,
       247.5       , 209.        , 187.        , 176.        ,
       165.        , 247.5       , 104.5       , 104.5       ,
       106.7       ,  93.5       ,  96.8       ,  50.6       ,
        95.7       ,  99.        , 104.5       , 124.3       ,
        99.        , 236.5       , 220.        , 231.        ,
       212.3       ,  96.8       ,  99.        , 104.5       ,
       114.91632653, 110.        , 115.5       , 110.        ,
        96.8       , 110.        , 181.5       , 192.5       ,
       168.3       , 165.        , 198.        , 187.        ,
       192.5       , 121.        ,  79.2       , 110.        ,
        96.8       ,  94.6       ,  99.        ,  77.        ,
        83.6       ,  71.5       ,  75.9       ,  66.        ,
        77.        , 104.5       ,  88.        ,  59.4       ,
        99.        ,  94.6       , 181.5       , 192.5 

6. **Boolean Indexing**

Find the average displacement of cars with an origin of 2 (Europe) using NumPy indexing.

In [61]:
displacement = df['displacement'].to_numpy()
origin = df['origin'].to_numpy()

avg_displacement_europe = np.mean(displacement[origin == 2])
avg_displacement_europe


np.float64(109.14285714285714)

7. **Matrix Operations**

Create a 2D NumPy array containing the columns mpg, horsepower, and weight.

Compute the dot product of this matrix with a given vector [1, 0.5, -0.2].

In [62]:
matrix = df[['mpg', 'horsepower', 'weight']].to_numpy()

vector = np.array([1, 0.5, -0.2])

matrix @ vector



array([-617.8, -641.1, -594.2, -595.6, -602.8, -754.2, -746.8, -740.9,
       -758.5, -660. , -612.6, -627.8, -662.2, -490.7, -402.9, -497.1,
       -488.3, -453.9, -355. , -318. , -465.9, -417. , -402.5, -364.3,
       -463.6, -805.5, -765.2, -760.4, -840.9, -355. , -379.8, -373.1,
          nan, -457.8, -619.3, -598.8, -597.4, -589.6, -745.3, -791.3,
       -740.3, -730.2, -889. , -851.2, -927.5, -519.4, -423.6, -587.4,
       -565.8, -378. , -351.6, -349.8, -345. , -291.1, -253.1, -309.8,
       -330. , -384.1, -360.2, -400.8, -416.6, -381.2, -759.3, -775.5,
       -737. , -735.3, -642.4, -811.6, -809.9, -799.2, -776.4, -398.5,
       -688.4, -741.6, -775.8, -726.4, -512.6, -442.2, -531.3, -377.3,
       -414. , -383.6, -429.7, -364.8, -349. , -719.5, -645.4, -712.1,
       -725.9, -665.4, -879.4, -804.8, -780.6, -758.4, -826.5, -865.7,
       -663.7, -553.7, -589.6, -521. , -542.2, -510.3, -341. , -913.4,
       -885.7, -832.8, -797.8, -489.8, -391.8, -423.2, -406.8, -361.8,
      

8. **Sorting**

Use NumPy to sort the cars by model_year in descending order and display the fi rst fi ve car names.

In [63]:
df.sort_values('model year', ascending=False)['car name'].head(5).tolist()



['chevy s-10', 'ford ranger', 'dodge rampage', 'vw pickup', 'ford mustang gl']

9. **Correlation**

Compute the Pearson correlation coeffi cient between mpg and weight using NumPy.


In [64]:
correlation = np.corrcoef(df['mpg'], df['weight'])[0, 1]
correlation


np.float64(-0.8317409332443352)

10. **Conditional Aggregates**

Calculate the mean mpg for cars grouped by the number of cylinders using NumPy techniques.

In [65]:
df.groupby('cylinders')['mpg'].mean()


cylinders
3    20.550000
4    29.286765
5    27.366667
6    19.985714
8    14.963107
Name: mpg, dtype: float64

# **Pandas Problems**

1. **Basic Exploration**

Load the dataset into a Pandas DataFrame. Display:

○ The first 10 rows

○ The total number of rows and columns

○ Summary statistics for numerical columns

In [66]:
# First 10 rows
df.head(10)


mpg  cylinders  displacement  horsepower  weight  acceleration  \
0  18.0          8         307.0       130.0    3504          12.0   
1  15.0          8         350.0       165.0    3693          11.5   
2  18.0          8         318.0       150.0    3436          11.0   
3  16.0          8         304.0       150.0    3433          12.0   
4  17.0          8         302.0       140.0    3449          10.5   
5  15.0          8         429.0       198.0    4341          10.0   
6  14.0          8         454.0       220.0    4354           9.0   
7  14.0          8         440.0       215.0    4312           8.5   
8  14.0          8         455.0       225.0    4425          10.0   
9  15.0          8         390.0       190.0    3850           8.5   

   model year  origin                   car name  
0          70       1  chevrolet chevelle malibu  
1          70       1          buick skylark 320  
2          70       1         plymouth satellite  
3          70       1              amc rebel sst  
4          70       1                ford torino  
5          70       1           ford galaxie 500  
6          70       1           chevrolet impala  
7          70       1          plymouth fury iii  
8          70       1           pontiac catalina  
9          70       1         amc ambassador dpl

In [67]:
# Shape
df.shape


(398, 9)

In [68]:
# Summary statistics
df.describe()


mpg   cylinders  displacement  horsepower       weight  \
count  398.000000  398.000000    398.000000  392.000000   398.000000   
mean    23.514573    5.454774    193.425879  104.469388  2970.424623   
std      7.815984    1.701004    104.269838   38.491160   846.841774   
min      9.000000    3.000000     68.000000   46.000000  1613.000000   
25%     17.500000    4.000000    104.250000   75.000000  2223.750000   
50%     23.000000    4.000000    148.500000   93.500000  2803.500000   
75%     29.000000    8.000000    262.000000  126.000000  3608.000000   
max     46.600000    8.000000    455.000000  230.000000  5140.000000   

       acceleration  model year      origin  
count    398.000000  398.000000  398.000000  
mean      15.568090   76.010050    1.572864  
std        2.757689    3.697627    0.802055  
min        8.000000   70.000000    1.000000  
25%       13.825000   73.000000    1.000000  
50%       15.500000   76.000000    1.000000  
75%       17.175000   79.000000    2.000000  
max       24.800000   82.000000    3.000000

2. **Filtering and Indexing**

Find all cars manufactured in 1975 with a weight less than 3000. Return the DataFrame with selected columns: car_name, weight, and mpg.


In [69]:
df[
    (df['model year'] == 75) & (df['weight'] < 3000)
  ][
    ['car name', 'weight', 'mpg']
]


car name  weight   mpg
167     toyota corolla    2171  29.0
168         ford pinto    2639  23.0
169        amc gremlin    2914  20.0
170      pontiac astro    2592  23.0
171      toyota corona    2702  24.0
172  volkswagen dasher    2223  25.0
173         datsun 710    2545  24.0
174         ford pinto    2984  18.0
175  volkswagen rabbit    1937  29.0
177         audi 100ls    2694  23.0
178        peugeot 504    2957  23.0
179        volvo 244dl    2945  22.0
180          saab 99le    2671  25.0
181   honda civic cvcc    1795  33.0

3. **Handling Missing Data**

Identify if there are any missing values in the dataset. Replace missing values in the horsepower column with the column's median.

In [70]:
# Check missing values
df.isnull().sum()


mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [71]:
# Replace missing horsepower with median
df['horsepower'].fillna(df['horsepower'].median(), inplace=True)


/tmp/ipython-input-2427930055.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['horsepower'].fillna(df['horsepower'].median(), inplace=True)


4. **Data Transformation**

Add a new column power_to_weight_ratio, calculated as horsepower / weight.

In [72]:
df['power_to_weight_ratio'] = df['horsepower'] / df['weight']
df[['power_to_weight_ratio']].head()


power_to_weight_ratio
0               0.037100
1               0.044679
2               0.043655
3               0.043694
4               0.040591

5. **Group By**

Group the cars by origin and calculate the mean mpg for each group.

In [73]:
df.groupby('origin')['mpg'].mean()


origin
1    20.083534
2    27.891429
3    30.450633
Name: mpg, dtype: float64

6. **Sorting**

Sort the DataFrame by mpg in descending order and display the top 10 cars with the highest mpg.

In [74]:
df.sort_values('mpg', ascending=False).head(10)


mpg  cylinders  displacement  horsepower  weight  acceleration  \
322  46.6          4          86.0        65.0    2110          17.9   
329  44.6          4          91.0        67.0    1850          13.8   
325  44.3          4          90.0        48.0    2085          21.7   
394  44.0          4          97.0        52.0    2130          24.6   
326  43.4          4          90.0        48.0    2335          23.7   
244  43.1          4          90.0        48.0    1985          21.5   
309  41.5          4          98.0        76.0    2144          14.7   
330  40.9          4          85.0        93.5    1835          17.3   
324  40.8          4          85.0        65.0    2110          19.2   
247  39.4          4          85.0        70.0    2070          18.6   

     model year  origin                         car name  \
322          80       3                        mazda glc   
329          80       3              honda civic 1500 gl   
325          80       2             vw rabbit c (diesel)   
394          82       2                        vw pickup   
326          80       2               vw dasher (diesel)   
244          78       2  volkswagen rabbit custom diesel   
309          80       2                        vw rabbit   
330          80       2             renault lecar deluxe   
324          80       3                       datsun 210   
247          78       3                   datsun b210 gx   

     power_to_weight_ratio  
322               0.030806  
329               0.036216  
325               0.023022  
394               0.024413  
326               0.020557  
244               0.024181  
309               0.035448  
330               0.050954  
324               0.030806  
247               0.033816

**Apply Function**

Create a new column performance_score using a custom function:


def performance_score(row):
  
  return row['mpg'] * row['acceleration'] / row['weight']

7. Apply this function to each row and store the result in the new column.


In [75]:
def performance_score(row):
    return row['mpg'] * row['acceleration'] / row['weight']

df['performance_score'] = df.apply(performance_score, axis=1)
df[['performance_score']].head()


performance_score
0           0.061644
1           0.046710
2           0.057625
3           0.055928
4           0.051754

8. **Visualization Preparation**

Generate a summary DataFrame with:


○ Average mpg, weight, and horsepower for each model_year.


In [76]:
summary_df = df.groupby('model year')[['mpg','weight','horsepower']].mean()
summary_df


mpg       weight  horsepower
model year                                    
70          17.689655  3372.793103  147.827586
71          21.250000  2995.428571  106.553571
72          18.714286  3237.714286  120.178571
73          17.100000  3419.025000  130.475000
74          22.703704  2877.925926   94.203704
75          20.266667  3176.800000  101.066667
76          21.573529  3078.735294  101.117647
77          23.375000  2997.357143  105.071429
78          24.061111  2861.805556   99.694444
79          25.093103  3055.344828  101.206897
80          33.696552  2436.655172   78.586207
81          30.334483  2522.931034   81.465517
82          31.709677  2453.548387   81.854839

9. **Exporting Data**

Save a subset of the data containing only mpg, cylinders, horsepower, and weight for cars with mpg > 30 into a CSV fi le named high_mpg_cars.csv.


In [77]:
high_mpg_cars = df[df['mpg'] > 30][['mpg', 'cylinders', 'horsepower', 'weight']]

high_mpg_cars.to_csv("high_mpg_cars.csv", index=False)


10. **Finding Anomalies**

Identify potential outliers in the mpg column using the Interquartile Range (IQR) method. Specifically:


● Calculate the IQR for mpg.

● Defi ne outliers as values less than Q1 - 1.5 * IQR or greater than Q3 + 1.5 * IQR.

● Create a DataFrame of cars classifi ed as outliers, displaying car_name, mpg, and model_year.

In [78]:
Q1 = df['mpg'].quantile(0.25)
Q3 = df['mpg'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers_df = df[
    (df['mpg'] < lower_bound) |
    (df['mpg'] > upper_bound)
][['car name', 'mpg', 'model year']]

outliers_df


car name   mpg  model year
322  mazda glc  46.6          80